=== cayblood/cucumber_presentation/examples/variants/cuke4ninja/resources/plainbook/plainbook.dtd
<!ENTITY % isonum SYSTEM "isonum.ent" >

%isonum;

<!ENTITY % isopub SYSTEM "isopub.ent" >

%isopub;

<!ENTITY % isolat1 SYSTEM "isolat1.ent" >

%isolat1;

<!ENTITY % contentblocks "p|code|ol|ul|img|todo|quote|index">
<!ENTITY % blockgroups "bibliography|section|note|important|sidebar|tip|try|avoid|try-vip|avoid-vip">
<!ENTITY % contentelements "#PCDATA|link|url|code|i|footnote|file|b|todo|ol|ul|img|sup|bib|index|define|quote">
<!ENTITY % codeelements "#PCDATA|i|b">
<!ENTITY % commonattribs "title CDATA #REQUIRED
id ID #IMPLIED
wikiname CDATA #IMPLIED">

<!ELEMENT chapter (%contentblocks;|%blockgroups;)+>
<!ATTLIST chapter 
	  %commonattribs;
>
<!ELEMENT preface (%contentblocks;|%blockgroups;)+>
<!ATTLIST preface 
	  %commonattribs;
>
<!ELEMENT appendix (%contentblocks;|%blockgroups;)+>
<!ATTLIST appendix 
	  %commonattribs;
>
<!ELEMENT colophon (%contentblocks;|%blockgroups;)+>
<!ATTLIST colophon 
	  %commonattribs;
>

<!ELEMENT section (%contentblocks;|%blockgroups;)+>
<!ATTLIST section 
	  %commonattribs;
>
<!ELEMENT note (%contentblocks;)+ >
<!ATTLIST note 
	  %commonattribs;
>
<!ELEMENT important (%contentblocks;)+ >
<!ATTLIST important 
	  %commonattribs;
>
<!ELEMENT sidebar (%contentblocks;)+>
<!ATTLIST sidebar 
	  %commonattribs;
>
<!ELEMENT p (%contentelements;)* >
<!ELEMENT code (%codeelements;)* >
<!ATTLIST code  
	file CDATA #IMPLIED
	part CDATA #IMPLIED
>
<!ELEMENT ul (li+) >
<!ELEMENT ol (li+) >
<!ELEMENT li (%contentelements;|quote)*  >
<!ELEMENT quote (%contentelements;|p)*  >
<!ELEMENT link EMPTY>
<!ATTLIST link  
	ref CDATA #REQUIRED
>  	
<!ELEMENT url EMPTY>
<!ATTLIST url  
	link CDATA #REQUIRED
	title CDATA #IMPLIED
> 
<!ELEMENT i (#PCDATA)>
<!ELEMENT define (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT todo (#PCDATA)>
<!ELEMENT footnote (%contentelements;)*  >
<!ELEMENT img EMPTY>
<!ATTLIST img
	id CDATA #IMPLIED  
	title CDATA #IMPLIED
	src CDATA #IMPLIED
	float CDATA #IMPLIED
	width CDATA #IMPLIED
> 
<!ELEMENT file (#PCDATA)>
<!ELEMENT tip (%contentblocks;)+>
<!ATTLIST tip 
	  %commonattribs;
>
<!ELEMENT try (%contentblocks;)+>
<!ATTLIST try 
	  %commonattribs;
	  context CDATA #REQUIRED
	  benefit CDATA #IMPLIED
>
<!ELEMENT avoid (%contentblocks;)+>
<!ATTLIST avoid 
	  %commonattribs;
	  context CDATA #REQUIRED
	  benefit CDATA #IMPLIED
>
<!ELEMENT try-vip (%contentblocks;)+>
<!ATTLIST try-vip 
	  %commonattribs;
	  benefit CDATA #IMPLIED
>
<!ELEMENT avoid-vip (%contentblocks;)+>
<!ATTLIST avoid-vip 
	  %commonattribs;
	  benefit CDATA #IMPLIED
>
<!ELEMENT bib EMPTY>
<!ATTLIST bib
	ref CDATA #REQUIRED  
>
<!ELEMENT bibliography EMPTY>
<!ELEMENT sup (%contentelements;|p)* >
<!ELEMENT index EMPTY>
<!ATTLIST index 
 primary CDATA #REQUIRED
 secondary CDATA #IMPLIED
 see CDATA #IMPLIED>

=== cayblood/cucumber_presentation/examples/variants/cuke4ninja/plainbook/specflow.xml
<!DOCTYPE chapter SYSTEM "../resources/plainbook/plainbook.dtd" >
<chapter title="Specflow" id="chp_specflow">
	<p>
		This is a para.
		Line breaks are ignored within the para
	</p>
 	<p>&lsquo;Quoted text&rsquo;</p>
	<p><i>italic text</i></p>
	<p>
		<ol>
			<li>
				Ordered list item
			</li>
		</ol>
		<ul>
			<li>Bullet Point</li>
		</ul>
	</p>
	<section title="Section" id="sec_specflow_example">
		<p>
			Make sure all the ids are unique.
		</p>
		<section title="Sub section" id="sec_specflow_subexample">
			<p>
				You can nest sections
			</p>
		</section>
		<section title="Linking and footnotes" id="sec_specflow_link">
			<p>
				You can link to other items using an id <link ref="sec_specflow_subexample" />.
			</p>
			<p>
				You can add footnotes with embedded urls.<footnote><url link="http://watin.sourceforge.net/apartmentstateinfo.html"></url></footnote>
			</p>
			<p>
				You can add footnotes with just text.<footnote>Punctuation comes before the footnote according to Gojko</footnote>
			</p>
			<sidebar title="Sidebars" id="sb-specflow">
				<p>
					Use sidebars for related steps
				</p>
			</sidebar>
		</section>
		<section title="Embedding code" id="sec_specflow_code">
			<p>
				You can embed code, the code can be split into parts using comments
			</p>
			<code file="dotnet/WebNinja/WatiNinja/App.config" part="apartment"/>
			<p>
				You can also put code inline
			</p>
			<code>
				Inline code example			
			</code>
		</section>
		
		<section title="Images" id="sec_specflow_images">
			<p>
				You can embed images, put the image into the images directory under the root. Make sure the image has a unique id. We also found Gojko's environment is case sensitive whereas mine isn't for image file names (and probably yours won't be as well)
			</p>
			<img src="codetrack-cukeadmin.png" id="img.specflow-cukeadmin" title="Example of an image"/>
		</section>
		<section title="Important" id="sec_specflow_important">
			<important title="Imprtant stuff can be highlighted">
	            <p>
					Like this.
	            </p>
	        </important>
		</section>
	</section> 
</chapter>
